require: rubocop-rspec

AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
